name: Create Production Builds

on:
  push:
    branches: ['main']

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: development
  download_android:
    needs: [build_android]
    type: get-build
    params:
      platform: android
      distribution: internal
      profile: development
