name: Create Production Builds

on:
  push:
    branches: ['main']

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: development
  download_android:
    needs: [build_android]
    type: run
    params:
      command: mkdir -p bin && eas build:download ${{ needs.build_android.outputs.buildId }} --output bin/
